language: node_js
node_js:
- node
before_install:
- sudo apt-get -qq update
- sudo apt-get install ncftp
script:
- bash deploy.sh
env:
  global:
  - secure: 3V/pZ5qJPtjZIbsISw+Yk0Q2Fjq/5OnMIqMT3pN9iYyMphwS4dZKcaqSu/bn0HgF+fmScHAQnP3lq34ePd35oltqr889jfSeo0tqiNE2m5xk+judyrvFNBlkuWpyaZi/OCh717+VH7WDk2Evfr0EZReOL4wIlgLWV6SCugVkOp44evuBY74FLlgDCsFoDP4i+QWUB4BgvK791dmVWbw91Q3GsoOyo3m9EPyJ25PQfNUSvanGoi2FhhyAVAuOPuLXJ93ic71lMfqo6suYlGSAICfcwaWmrTvPBvW0ROp2dtMvwPkB8FRIiy8iTDs2xWUWyc1YmxSWYfPxkYgM2UN6TW7iVxtyxHvCj+G3b6+MZqc2reY0Td2s6dRwsIDD3ss8DZGWQI5DYRZkc50wfo9diGnr7FM+5xGprVFsNYxOvueULmq9+vGZTm9nDi7FW9hq3x5wilLkOvObDVbe5ep2FeayaLij0WMio5jTwN1umiX1sP8KH2FJjHf7PGFRfU5mGNwbB+jhL8ufgBwLLKBj2/ZWHQ0BuRuuzne2gaRPRz/45ZslmXIM9rpArV6MVKv7j7ek3NzHthDQDEdYOKLpLxzg5g/x+gBFCzKnS5W7fGwf9YubBshjOFpD0bIqWhW6yWV2xI/Bt19Z1obEolKhABW8p84dWozCpmjv4k27SuM=
  - secure: FUgs5v56Z91W64EFLGb4j1U/MjBFdWPLHETPCjVGMI2OtUStY4umPsBWui7Mvx7i5MhDAgzqYBkPswPMBosqGCQLWuYs5mqQJtZyO5WnLlVBPlWkgO96BMeDRa8ykekdtGOX1g71i4q1tlXqdCje+bDNyFy/XFdfjYGnt3woajR/wxPob+1bqGH/o01jmA9WE1l+0lp4SZfmTt28oEv7kJsXFfcBOAbhsqr4qnaX7Om58kBj6iAwaueOQof0uj9+OxWDg1B7AzTqyW6/jOY9KnFSldPJVUlt1yms+0J9+9rIhkMmsala4WQnapu7J007SzgTRl0GgnTAu3KkBlcJxG90iRYxL2kVUoobsf3r05OlPHLGPWZzqM2DVR9v3+MT1jG6CMCi7AMaJGWpjqXAEfEO9HSU3kAj2RSRkoY93MjBRbTYoHHCdIhcLItM2oDTpn8kezOFlyRBROHNVf9UUcp9pIVydy2BwWlw7ngI/yOcs4AstKRfEnObTkgA1l4xKBeYbF5IGTs34KoOlStQ534P9Pwub4/imwZ+FwSjFRZQBfORjGT8yVmDRH195x537yMP4hNM89lX5nvw9dTzgxQth/Bl/wbOFTVOMLozrKneH6EpQmKF/JiXiBIhaJpxBixVhXPu2Pd8g0NYrlRyk3oPE5tYf038hKqa7JmgCxs=
