language: node_js
node_js:
- 'node'
env:
  global:
  - secure: kb+aU1FOzuWXActEqvqWO0tvlrowB23vcS6gVyA3nfnmx98/TaT3gh9fzfRXLr4ikoEQmnG22ruc5KDcDlwufixs5zCwuWMmyrbmI7DjdLWLMU6DGEBomZcUt78ljt07VjOdiwhpYXZ2fk+ZfBC+j9I5Hoc6S/gb+0hcbaCtX3lCCKnhEA2MrHhrKaAKa0Rx5PCzMpbkj1CrjES/4vtUfJKDtrPgFkFwJegIEMIiymqMcd8LrG0LO7lhJ/LOtV3Aq1Up/o5YoBr4rDGM2ZbKkfgwjKvR9t6/qN8pDW5839zGw3GXE7SN4YLnqJLOk454uyUtNwIvGcKsnbRFbHSxkr4U/J4ZiA6c3Wi1Cu4SADg+fGXr/zklqXgovkghKJ2QilFAv5ZXG09wj7ssTJsAkwmF8VSXf7BkUPzUgJsi2hg76w3TQVZjlbG10zC0LRMvJOcECUvNBSBSiYo85ndU6iCEsDeRaYbNAVr93X7u5XQjTPk5ILJTKbRsT37Z4chCkc2lLkKtg57s7x1svmlU/fBgbXi7AvdL4zV4u5r2+6NmOON+13XDLrSmdWCVATGsw/IG9mkia5+5bbM4RZQKqfrUOvf/r2604AkFEgusj+mSupjrG6XtZMN1xb/BwnfFPLrO10GHfBO9+th/wdmGzZplHy4xyvCLjHaDenyKH8Q=
  - secure: 4x+vHgSVS40CByGHxI5mMz/VAic3cBul0Z80SmgVsFVqM/lY9HlzEoh7pvnMo6kyAX5quJ77TWZxAJkZSRM0y/t9gCD0B+q8CcFjkLIOMuaw4gCipNFDlD/GI2aCqDW/FN0X+s4Oo/3VCwud6lCEj6ODq8YcDt3gARGn01t4+BGIN6IWPbCbukyAMVnH0qMXOgY6VG/40GfsFT+Z5+563EfS36oqk9Qg6RZ5SkMe+draHIKg/4p7/zcDlesrHmwYg7EhuGZgqx6MB1+G/chm/xUnlRsQE/FE8598wM8BrJY07lnMM0/es4J1a6pG6d+914tpBjFitHDLwTuFJRoomYNf9QNngYhUs8ONvAeMUhmEw0ZcFOzQvjYt/gaUPBYfH6AoTt3lHa0Z4HBmoeBdhktpV3HXEbmc+DmZli+YTL3e/hjmTd2Cv8Yc3TX9Iagb8SLElOjX2qHjBug6/2Tt3S4GhsLCd30OqfbKkGL6OF4++c00GO3GR0az4PjTwRTFG5U9nw0gfMu6+SN7xax6AIGnqM5y0VgnWvkW2VNhCjNU36tQYgmKiZuPOaeiS00R+CC3DqVlTCFLR65STIxAMWdvJLbFexFcT9r+BBsYASyfOfaPvl6XJyfix9w0EeE0OjavyCTIFQIiVvAL17ikLwv6o8im5FKJgNIeA95l6tk=
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ncftp
script:
  - bash deploy.sh
